export const TRY_TO_REGISTER = "TRY_TO_REGISTER";
export const SUCCEEDED_TO_REGISTER = "SUCCEEDED_TO_REGISTER";
export const FAILED_TO_REGISTER = "FAILED_TO_REGISTER";

export const TRY_TO_SIGN_IN = "TRY_TO_SIGN_IN";
export const SUCCEEDED_TO_SIGN_IN = "SUCCEEDED_TO_SIGN_IN";
export const FAILED_TO_SIGN_IN = "FAILED_TO_SIGN_IN";

export const TRY_TO_SIGN_OUT = "TRY_TO_SIGN_OUT";
export const SUCCEEDED_TO_SIGN_OUT = "SUCCEEDED_TO_SIGN_OUT";
export const FAILED_TO_SIGN_OUT = "FAILED_TO_SIGN_OUT";

export const TRY_TO_FETCH_BROTTSPLATS_EVENTS =
  "TRY_TO_FETCH_BROTTSPLATS_EVENTS";
export const SUCCEEDED_TO_FETCH_BROTTSPLATS_EVENTS =
  "SUCCEEDED_TO_FETCH_BROTTSPLATS_EVENTS";
export const FAILED_TO_FETCH_BROTTSPLATS_EVENTS =
  "FAILED_TO_FETCH_BROTTSPLATS_EVENTS";

export const TRY_TO_FETCH_DB_EVENTS = "TRY_TO_FETCH_DB_EVENTS";
export const SUCCEEDED_TO_FETCH_DB_EVENTS = "SUCCEEDED_TO_FETCH_DB_EVENTS";
export const FAILED_TO_FETCH_DB_EVENTS = "FAILED_TO_FETCH_DB_EVENTS";

export const TRY_TO_SAVE_DB_EVENT = "TRY_TO_SAVE_DB_EVENT";
export const SUCCEEDED_TO_SAVE_DB_EVENT = "SUCCEEDED_TO_SAVE_DB_EVENT";
export const FAILED_TO_SAVE_DB_EVENT = "FAILED_TO_SAVE_DB_EVENT";

export const TRY_TO_FETCH_MAP = "TRY_TO_FETCH_MAP";
export const SUCCEEDED_TO_FETCH_MAP = "SUCCEEDED_TO_FETCH_MAP";
export const FAILED_TO_FETCH_MAP = "FAILED_TO_FETCH_MAP";
